# Site settings
title: Blog of Pushpi Upadhyay
email: pushpi.upadhyay@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A housewife, lawyer and corporate trainer.
aseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pushpi.incorpify.in" # the base hostname & protocol for your site
twitter_username: 
#github_username:  jekyll

# Build settings
markdown: kramdown
